flask_app/app/blueprint_api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, template_folder='templates')

from app.blueprint_api import routes

flask_app/app/blueprint_api/routes.py
from flask import request, render_template

from src.forms import OrgForm, RepoForm, CommitForm
from app.blueprint_api import bp
from app import Gitea


@bp.route('/')
def api():
    return render_template('gitea_api.html')


@bp.route('/clean', methods=['GET'])
def clean():
    Gitea.clean_server()
    return render_template('clean_server/clean_success.html')


@bp.route('/create_org', methods=['GET', 'POST'])
def create_org():
    form = OrgForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        try:
            response = Gitea.create_org(name=username)
        except ValueError as err:
            return render_template('create_org/create_org_fail.html', username=username, code=err.args[0],
                                   response=err.args[1])
        else:
            return render_template('create_org/create_org_success.html', username=username, response=response)
    else:
        return render_template('create_org/create_org.html')


@bp.route('/delete_org', methods=['GET', 'POST'])
def delete_org():
    form = OrgForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        try:
            response = Gitea.delete_org(name=username)
        except ValueError as err:
            return render_template('delete_org/delete_org_fail.html', username=username, code=err.args[0],
                                   response=err.args[1])
        else:
            return render_template('delete_org/delete_org_success.html', username=username, response=response)
    else:
        return render_template('delete_org/delete_org.html')


@bp.route('/get_org', methods=['GET', 'POST'])
def get_org():
    form = OrgForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        try:
            response = Gitea.get_org(name=username)
        except ValueError as err:
            return render_template('get_org/get_org_fail.html', username=username, code=err.args[0],
                                   response=err.args[1])
        else:
            return render_template('get_org/get_org_success.html', username=username, response=response)
    else:
        return render_template('get_org/get_org.html')


@bp.route('/create_repo', methods=['GET', 'POST'])
def create_repo():
    form = RepoForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        reponame = form.reponame.data
        try:
            response = Gitea.create_repo(username=username, reponame=reponame)
        except ValueError as err:
            return render_template('create_repo/create_repo_fail.html', username=username, reponame=reponame,
                                   code=err.args[0], response=err.args[1])
        else:
            return render_template('create_repo/create_repo_success.html', username=username, reponame=reponame,
                                   response=response)
    else:
        return render_template('create_repo/create_repo.html')


@bp.route('/get_repo', methods=['GET', 'POST'])
def get_repo():
    form = RepoForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        reponame = form.reponame.data
        try:
            response = Gitea.get_repo(username=username, reponame=reponame)
        except ValueError as err:
            return render_template('get_repo/get_repo_fail.html', username=username, reponame=reponame,
                                   code=err.args[0], response=err.args[1])
        else:
            return render_template('get_repo/get_repo_success.html', username=username, reponame=reponame,
                                   response=response)
    else:
        return render_template('get_repo/get_repo.html')


@bp.route('/delete_repo', methods=['GET', 'POST'])
def delete_repo():
    form = RepoForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        reponame = form.reponame.data
        try:
            response = Gitea.delete_repo(username=username, reponame=reponame)
        except ValueError as err:
            return render_template('delete_repo/delete_repo_fail.html', username=username, reponame=reponame,
                                   code=err.args[0], response=err.args[1])
        else:
            return render_template('delete_repo/delete_repo_success.html', username=username, reponame=reponame,
                                   response=response)
    else:
        return render_template('delete_repo/delete_repo.html')


@bp.route('/get_commit', methods=['GET', 'POST'])
def get_commit():
    form = CommitForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        reponame = form.reponame.data
        commit = form.commit.data
        try:
            response = Gitea.get_commit(username=username, reponame=reponame, commit=commit)
        except ValueError as err:
            return render_template('get_commit/get_commit_fail.html', username=username, reponame=reponame,
                                   commit=commit, code=err.args[0], response=err.args[1])
        else:
            return render_template('get_commit/get_commit_success.html', username=username, reponame=reponame,
                                   commit=commit, response=response)
    else:
        return render_template('get_commit/get_commit.html')

flask_app/app/blueprint_api/templates/clean_server/clean_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cleaning success</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> Server cleaned successfully! </div>
    <br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/create_org/create_org.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Org create</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center">
        <div> Create an organization </div>
        <br><br>
        <form method="post">
            <label for="username"> Enter an organization name </label>
            <br>
            <input id="username" name="username" type="text">
            <br>
            <input type="submit" value="Enter">
        </form>
    </div>
    <br><br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/create_org/create_org_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Org create fail</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> Failed to create organization [{{username}}] </div>
    <div class="font" style="font-size: large"> Status code: {{code}} </div>
    <div class="font" style="font-size: large"> Response: {{response}} </div>
    <br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/create_org/create_org_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Org create success</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> An organization [{{username}}] created successfully! </div>
    <br>
    <div class="font" style="font-size: large">
        <table border = 1 width = 80%>
            {% for key in response %}
                <tr>
                    <td> {{key}} </td>
                    <td> {{response[key]}} </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/create_repo/create_repo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo create</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center">
        <div> Create a repo (in org) </div>
        <br><br>
        <form method="post">
            <label for="username"> Enter an organization name: </label>
            <input id="username" name="username" type="text">
            <br>
            <label for="reponame"> Enter a repo name: </label>
            <input id="reponame" name="reponame" type="text">
            <br>
            <input type="submit" value="Enter">
        </form>
    </div>
    <br><br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/create_repo/create_repo_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo create fail</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> Failed to create a repo [{{reponame}}] in org [{{username}}]</div>
    <div class="font" style="font-size: large"> Status code: {{code}} </div>
    <div class="font" style="font-size: large"> Response: {{response}} </div>
    <br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/create_repo/create_repo_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo create success</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> A repo [{{reponame}}] in org [{{username}}] created successfully! </div>
    <br>
    <div class="font" style="font-size: large">
        <table border = 1 width = 80%>
            {% for key in response %}
                <tr>
                    <td> {{key}} </td>
                    <td> {{response[key]}} </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/delete_org/delete_org.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Org delete</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center">
        <div> Delete an organization </div>
        <br><br>
        <form method="post">
            <label for="username"> Enter an organization name </label>
            <br>
            <input id="username" name="username" type="text">
            <br>
            <input type="submit" value="Enter">
        </form>
    </div>
    <br><br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/delete_org/delete_org_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Org delete fail</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> Failed to delete organization [{{username}}] </div>
    <div class="font" style="font-size: large"> Status code: {{code}} </div>
    <div class="font" style="font-size: large"> Response: {{response}} </div>
    <br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/delete_org/delete_org_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Org delete success</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> An organization [{{username}}] deleted successfully! </div>
    <br>
    <div class="font" style="font-size: large">
        <table border = 1 width = 80%>
            {% for key in response %}
                <tr>
                    <td> {{key}} </td>
                    <td> {{response[key]}} </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/delete_repo/delete_repo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo delete</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center">
        <div> Delete a repo (in org) </div>
        <br><br>
        <form method="post">
            <label for="username"> Enter an organization name: </label>
            <input id="username" name="username" type="text">
            <br>
            <label for="reponame"> Enter a repo name: </label>
            <input id="reponame" name="reponame" type="text">
            <br>
            <input type="submit" value="Enter">
        </form>
    </div>
    <br><br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/delete_repo/delete_repo_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo delete fail</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> Failed to delete a repo [{{reponame}}] in org [{{username}}]</div>
    <div class="font" style="font-size: large"> Status code: {{code}} </div>
    <div class="font" style="font-size: large"> Response: {{response}} </div>
    <br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/delete_repo/delete_repo_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo delete success</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> A repo [{{reponame}}] in org [{{username}}] deleted successfully! </div>
    <br>
    <div class="font" style="font-size: large">
        <table border = 1 width = 80%>
            {% for key in response %}
                <tr>
                    <td> {{key}} </td>
                    <td> {{response[key]}} </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/get_commit/get_commit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Commit get</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center">
        <div> Get a commit</div>
        <br><br>
        <form method="post">
            <label for="username"> Enter an organization name: </label>
            <input id="username" name="username" type="text">
            <br>
            <label for="reponame"> Enter a repo name: </label>
            <input id="reponame" name="reponame" type="text">
            <br>
            <label for="commit"> Enter a commit sha: </label>
            <input id="commit" name="commit" type="text">
            <br>
            <input type="submit" value="Enter">
        </form>
    </div>
    <br><br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/get_commit/get_commit_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Commit get fail</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> Failed to get a commit [{{commit}}] in repo [{{reponame}}] in org [{{username}}]</div>
    <div class="font" style="font-size: large"> Status code: {{code}} </div>
    <div class="font" style="font-size: large"> Response: {{response}} </div>
    <br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/get_commit/get_commit_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Commit get success</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> A commit [{{commit}}] in repo [{{reponame}}] in org [{{username}}] got successfully! </div>
    <br>
    <div class="font" style="font-size: large">
        <table border = 1 width = 80%>
            {% for key in response %}
                <tr>
                    <td> {{key}} </td>
                    <td> {{response[key]}} </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/get_repo/get_repo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo get</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center">
        <div> Get a repo (in org) </div>
        <br><br>
        <form method="post">
            <label for="username"> Enter an organization name: </label>
            <input id="username" name="username" type="text">
            <br>
            <label for="reponame"> Enter a repo name: </label>
            <input id="reponame" name="reponame" type="text">
            <br>
            <input type="submit" value="Enter">
        </form>
    </div>
    <br><br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/get_repo/get_repo_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo get fail</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> Failed to get a repo [{{reponame}}] in org [{{username}}]</div>
    <div class="font" style="font-size: large"> Status code: {{code}} </div>
    <div class="font" style="font-size: large"> Response: {{response}} </div>
    <br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/get_repo/get_repo_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repo get success</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br>
    <div class="font" align="center"> A repo [{{reponame}}] in org [{{username}}] got successfully! </div>
    <br>
    <div class="font" style="font-size: large">
        <table border = 1 width = 80%>
            {% for key in response %}
                <tr>
                    <td> {{key}} </td>
                    <td> {{response[key]}} </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>

flask_app/app/blueprint_api/templates/gitea_api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gitea API options</title>
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='fonts.css')}}">
    <link type=" text/css" rel="stylesheet" href="{{url_for('static', filename='links.css')}}">
</head>

<body>
    <br><br><br>
    <div class="font" align="center"> Choose an option: </div>
    <br><br>
    <div class="font" align="center">
        <a href="{{url_for('api.create_org')}}"> Create an organization</a>
        <br>
        <a href="{{url_for('api.get_org')}}"> Get an organization</a>
        <br>
        <a href="{{url_for('api.delete_org')}}"> Delete an organization</a>
        <br><br>
        <a href="{{url_for('api.create_repo')}}"> Create a repo in organization</a>
        <br>
        <a href="{{url_for('api.get_repo')}}"> Get a repo in organization</a>
        <br>
        <a href="{{url_for('api.delete_repo')}}"> Delete a repo in organization</a>
        <br><br>
        <a href="{{url_for('api.get_commit')}}"> Get a commit</a>
        <br><br>
        <a href="{{url_for('api.clean')}}"> Clean server</a>
    </div>
    <br><br>
    <div class="font" align="center">
        <a href="{{url_for('main.start_func')}}"> Return to main page</a>
    </div>
</body>
</html>